CREATE TABLE CURRENCY_PAIR
(
    ID              integer generated by default as identity primary key,
    BASE_CHARCODE   varchar(5),
    QOUTED_CHARCODE varchar(5),
    DESCRIPTION     varchar(100)
);