INSERT INTO CURRENCY_PAIR (BASE_CHARCODE, QOUTED_CHARCODE, DESCRIPTION)
VALUES ('USD', 'RUB', 'American dollar and Russian ruble');

INSERT INTO CURRENCY_PAIR (BASE_CHARCODE, QOUTED_CHARCODE, DESCRIPTION)
VALUES ('EUR', 'RUB', 'Euro and Russian ruble');
